apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdd-pv
spec:
  capacity:
    storage: 1900Gi  # 2TB에서 시스템 여유공간 확보
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-storage
  local:
    path: /mnt/hdd
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-node  # 노드 이름 설정 필요