---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hdfs-auth
  namespace: default
spec:
  basicAuth:
    secret: hdfs-auth-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hdfs-namenode-ingress-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hdfs.mireu.xyz`)
      kind: Rule
      services:
        - name: listener-hdfs-cluster-namenode-default-0
          port: 9870
      middlewares:
        - name: redirect-https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hdfs-namenode-ingress-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hdfs.mireu.xyz`)
      kind: Rule
      services:
        - name: listener-hdfs-cluster-namenode-default-0
          port: 9870
      middlewares:
        - name: hdfs-auth
  tls:
    secretName: cloudflare-origin-cert
