# deployments/monitoring/grafana-values.yaml
grafana:
  adminPassword: "prom-operator"
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
    hosts:
      - "grafana.mireu.xyz"
    tls:
      - secretName: grafana-tls
        hosts:
          - "grafana.mireu.xyz"
  persistence:
    enabled: true
    type: pvc
    storageClassName: "nvme-storage"
    accessModes:
      - ReadWriteOnce
    size: 10Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "nvme-storage"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
