apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
  namespace: datascience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-operator
  template:
    metadata:
      labels:
        app: spark-operator
    spec:
      serviceAccountName: spark-operator
      containers:
      - name: spark-operator
        image: gcr.io/spark-operator/spark-operator:v1beta2-1.3.3-3.1.1
        args:
        - "-v=2"
        - "-namespace=datascience"
        - "-enable-metrics=true"
        resources:
          limits:
            cpu: "5"
            memory: "10Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"