---
apiVersion: v1
kind: Namespace
metadata:
  name: datascience
  labels:
    name: datascience
    purpose: data-analysis
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    purpose: data-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: system-monitoring
