apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
  namespace: datascience
spec:
  serviceName: hadoop-namenode
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
      - name: namenode
        image: apache/hadoop:3
        ports:
        - containerPort: 9000
          name: namenode
        - containerPort: 9870
          name: http
        env:
        - name: HADOOP_CUSTOM_CONF_DIR
          value: /etc/hadoop/conf
        volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop/dfs/name
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
  volumeClaimTemplates:
  - metadata:
      name: hadoop-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: hdd-storage
      resources:
        requests:
          storage: 500Gi